[package]
name = "num"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nicholas.lordello@gnosis.pm>"]
edition = "2018"
build = "build/main.rs"

[dependencies]

[build-dependencies]
cc = "^1.0.52"
