[package]
name = "ethnum"
version = "1.0.0"
authors = ["Nicholas Rodrigues Lordello <nicholas.lordello@gnosis.pm>"]
edition = "2018"

[features]
llvm-intrinsics = ["ethnum-intrinsics"]

[dependencies]
ethnum-intrinsics = { version = "1.0.0", path = "intrinsics", optional = true }
